In [1]:
import numpy as np


In [2]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])

In [3]:
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

In [4]:
vector_row

array([1, 2, 3])

In [5]:
vector_column

array([[1],
       [2],
       [3]])

In [6]:
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [7]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [8]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])

In [9]:
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])